services:
  postgres-test:
    image: postgres:17-alpine
    container_name: key-service-postgres-test-1
    environment:
      POSTGRES_DB: key_service_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432" # Use different port to avoid conflicts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5 # Use tmpfs for temp directory instead

